cloud_dependent_pkg: &cloud_dependent_pkg "commands"

functions:
  "fetch_go113":
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          wget --quiet ${go_url}
          tar xvf ./go1*gz
  "fetch_yarn":
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          curl --silent -OL ${yarn_url}
          tar zvxf latest.tar.gz
          mv yarn-* yarn
  "setup_node": &setup_node
      command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          export ROOT_DIR=`pwd`
          export NVM_DIR="$ROOT_DIR/.nvm"
          if [ ! -d "$NVM_DIR" ]; then
            git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
            cd "$NVM_DIR"
            git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
          fi
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install ${node_version}
  "setup_project":
    - command: git.get_project
      params:
        directory: realm-cli

tasks:
  - name: test_unit
    exec_timeout_secs: 3600
    commands:
      - func: "fetch_go113"
      - func: "fetch_yarn"
      - func: "setup_project"
      - command: shell.exec
        params:
          shell: "bash"
          script: |
            set -v
            set -e
            export ROOT_DIR=`pwd`
            export PATH="$ROOT_DIR:$PATH"
            export GOROOT=$ROOT_DIR/go
            export PATH=$GOROOT/bin:$PATH
            cd $ROOT_DIR/realm-cli
            go test -v -covermode=count -coverprofile=$ROOT_DIR/cover.out $(go list github.com/10gen/realm-cli/...) > $ROOT_DIR/realm-cli.suite
      - command: s3.put
        params:
          aws_key: ${test_aws_key}
          aws_secret: ${test_aws_secret}
          local_file: cover.out
          remote_file: ${task_id}/cover.out
          bucket: baas-test-artifacts
          content_type: text/plain
          permissions: public-read


  - name: lint
    commands:
      - func: "fetch_go113"
      - func: "setup_project"
      - command: shell.exec
        params:
          shell: "bash"
          script: |
            export ROOT_DIR=`pwd`
            export GOROOT=$ROOT_DIR/go
            export PATH=$GOROOT/bin:$PATH
            cd $ROOT_DIR/realm-cli
            go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./...


post:
  - command: gotest.parse_files
    params:
      files: ["*.suite"]

buildvariants:
- name: rhel70
  display_name: rhel70
  run_on:
    - rhel70
  expansions:
    go_url: "https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz"
    yarn_url: "https://s3.amazonaws.com/stitch-artifacts/yarn/latest.tar.gz"
    node_version: 12.16.2
    version: 0.0.0
  tasks:
  - name: test_unit
  - name: lint
